downgrade ruby racer gem because the build is failing.
make[3]: Entering directory `/tmp/wakame-vdc/frontend/admin/vendor/bundle/ruby/1.9.1/gems/therubyracer-0.11.0/ext/v8'
compiling rr.cc
compiling backref.cc
compiling message.cc
compiling v8.cc
v8.cc: In static member function 'static VALUE rr::V8::IdleNotification(int, VALUE*, VALUE)':
v8.cc:29: error: no matching function for call to 'v8::V8::IdleNotification(int)'
/usr/include/v8.h:3104: note: candidates are: static bool v8::V8::IdleNotification()
make[3]: *** [v8.o] Error 1
make[3]: Leaving directory `/tmp/wakame-vdc/frontend/admin/vendor/bundle/ruby/1.9.1/gems/therubyracer-0.11.0/ext/v8'